---
- src: geerlingguy.java
- src: geerlingguy.nginx
- src: geerlingguy.elasticsearch
- src: geerlingguy.elasticsearch-curator
- src: https://github.com/samyscoub/ansible-role-kibana.git
  name: geerlingguy.kibana
- src: geerlingguy.logstash
- src: geerlingguy.logstash-forwarder
